backoffice/missions/urls.py
from django.urls import path

from missions.views import assignment, default_assignments, mission, question, ship

urlpatterns = [
    path("", mission.ListView.as_view(), name="mission_list"),
    path("new", mission.CreateView.as_view(), name="mission_create"),
    path("<int:pk>/", mission.DetailView.as_view(), name="mission_detail"),
    path("<int:pk>/delete", mission.DeleteView.as_view(), name="mission_delete"),
    path("<int:pk>/edit", mission.UpdateView.as_view(), name="mission_update"),
    path("ships/", ship.ListView.as_view(), name="ship_list"),
    path(
        "ships/new", ship.CreateView.as_view(), name="ship_create"
    ),  # TODO: Replace 'new' with 'add'
    path("ships/<int:pk>/edit/", ship.UpdateView.as_view(), name="ship_update"),
    path("ships/<int:pk>/delete/", ship.DeleteView.as_view(), name="ship_delete"),
    path(
        "ships/<int:ship_id>/default-assignments/",
        default_assignments.ListView.as_view(),
        name="default_assignment_list",
    ),
    path(
        "ships/<int:ship_id>/default-assignments/add/",
        default_assignments.CreateView.as_view(),
        name="default_assignment_create",
    ),
    path(
        "ships/<int:ship_id>/default-assignments/<int:pk>/edit/",
        default_assignments.UpdateView.as_view(),
        name="default_assignment_update",
    ),
    path(
        "ships/<int:ship_id>/default-assignments/<int:pk>/delete",
        default_assignments.DeleteView.as_view(),
        name="default_assignment_delete",
    ),
    path(
        "<int:mission__id>/assignments/new",
        assignment.CreateView.as_view(),
        name="assignment_create",
    ),
    path(
        "<int:mission__id>/assignments/<int:pk>/delete",
        assignment.DeleteView.as_view(),
        name="assignment_delete",
    ),
    path(
        "<int:mission__id>/assignments/<int:pk>/send_mail",
        assignment.EmailView.as_view(),
        name="assignment_mail",
    ),
    path(
        "<int:mission__id>/assignments/<int:assignment__id>/assignee",
        assignment.UpdateView.as_view(),
        name="assignee",
    ),
    path("questions/", question.ListView.as_view(), name="question_list"),
    path("questions/add", question.CreateView.as_view(), name="question_create"),
    path(
        "questions/<int:pk>/delete",
        question.DeleteView.as_view(),
        name="question_delete",
    ),
    path(
        "questions/<int:pk>/edit", question.UpdateView.as_view(), name="question_update"
    ),
]

backoffice/seawatch_registration/urls.py
from django.urls import path

from seawatch_registration.views import (
    availability,
    document,
    position,
    profile,
    question,
    registration_process,
    skill,
)

urlpatterns = [
    path("profile/show/", profile.DetailView.as_view(), name="profile_detail"),
    path("profile/add/", profile.ProfileCreateView.as_view(), name="profile_create"),
    path("profile/edit/", profile.UpdateView.as_view(), name="profile_update"),
    path("documents/", document.ListView.as_view(), name="document_list"),
    path(
        "documents/add/", document.DocumentCreateView.as_view(), name="document_create"
    ),
    path(
        "documents/<int:document_id>/edit",
        document.UpdateView.as_view(),
        name="document_update",
    ),
    path(
        "documents/<int:document_id>/delete",
        document.DeleteView.as_view(),
        name="document_delete",
    ),
    path(
        "documents/<int:document_id>/<str:file_name>",
        document.GetDocumentAttachment.as_view(),
        name="document_attachment_get",
    ),
    path(
        "questions/edit/",
        question.AnsweringQuestionsView.as_view(),
        name="question_answer",
    ),
    path(
        "positions/edit/",
        position.PositionUpdateView.as_view(),
        name="requested_position_update",
    ),
    path("skills/edit/", skill.SkillsUpdateView.as_view(), name="skill_update"),
    path(
        "availabilities/",
        availability.AvailabilityListView.as_view(),
        name="availability_list",
    ),
    path(
        "availabilities/add/",
        availability.CreateView.as_view(),
        name="availability_create",
    ),
    path(
        "registration/",
        registration_process.View.as_view(),
        name="registration_process",
    ),
]

backoffice/applications/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from seawatch_registration.models import Position

from .service import ImportedApplicationDTO


class Application(models.Model):
    name = models.CharField(max_length=255)
    phone_number = PhoneNumberField()
    requested_positions = models.ManyToManyField(Position)
    # TODO: Propper Email field
    email = models.CharField(max_length=255)

    @classmethod
    def from_imported_application(cls, imported_application):
        return cls(
            name=imported_application.name,
            phone_number=imported_application.phone_number,
        )

    def __str__(self):
        return self.name


class Language(models.Model):
    code = models.CharField(max_length=3)
    points = models.IntegerField()

    application = models.ForeignKey(
        Application, on_delete=models.CASCADE, related_name="languages"
    )


class ImportedApplication(models.Model):
    uid = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    phone_number = PhoneNumberField()
    created = models.DateTimeField(editable=False)

    @classmethod
    def from_data_transfer_object(cls, dto: ImportedApplicationDTO):
        return cls(
            name=dto.name,
            uid=dto.uid,
            created=dto.created,
            phone_number=dto.phone_number,
        )


class ImportedLanguage(models.Model):
    code = models.CharField(max_length=3)
    points = models.IntegerField()

    application = models.ForeignKey(
        ImportedApplication, on_delete=models.CASCADE, related_name="languages"
    )


class Volunteer(models.Model):
    name = models.CharField(max_length=255)
    phone_number = PhoneNumberField()
    # TODO: Propper Email field
    email = models.CharField(max_length=255)

    def __str__(self):
        return self.name

backoffice/assessments/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from seawatch_registration.models import Profile


class Assessment(models.Model):
    profile = models.ForeignKey(
        Profile, on_delete=models.CASCADE, verbose_name=_("Profile")
    )

    REJECTED = "rejected"
    ACCEPTED = "accepted"
    PENDING = "pending"

    ASSESSMENT_STATUS = [
        (PENDING, _("pending")),
        (ACCEPTED, _("accepted")),
        (REJECTED, _("rejected")),
    ]
    status = models.CharField(
        max_length=10, choices=ASSESSMENT_STATUS, verbose_name=_("Status")
    )
    comment = models.TextField(blank=True, verbose_name=_("Comment"))

    class Meta:
        permissions = (("can_assess_profiles", _("Set assessments for profiles")),)

backoffice/missions/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils import FieldTracker

from seawatch_registration.models import Position


# Create your models here.
class Ship(models.Model):
    name = models.CharField(max_length=30, verbose_name=_("Name"))

    def __str__(self):
        return self.name


class Mission(models.Model):
    name = models.CharField(max_length=50, verbose_name=_("Name"))
    start_date = models.DateField(verbose_name=_("Start date"))
    end_date = models.DateField(verbose_name=_("End date"))
    ship = models.ForeignKey(Ship, on_delete=models.CASCADE, verbose_name=_("Ship"))

    def __str__(self):
        return self.ship.name + ": " + self.name

    def get_assigned_users(self):
        return User.objects.filter(assignments__mission=self).distinct()


class Assignment(models.Model):
    mission = models.ForeignKey(
        Mission, on_delete=models.CASCADE, verbose_name=_("Mission")
    )
    position = models.ForeignKey(
        Position, on_delete=models.CASCADE, verbose_name=_("Position")
    )
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        default=None,
        blank=True,
        null=True,
        related_name="assignments",
    )
    confirmed = models.BooleanField(default=False, verbose_name=_("Confirmed"))
    email_sent = models.BooleanField(default=False, verbose_name=_("Email sent"))

    tracker = FieldTracker(fields=["user"])


class DefaultAssignment(models.Model):
    position = models.ForeignKey(
        Position, on_delete=models.CASCADE, verbose_name=_("Position")
    )
    quantity = models.IntegerField(verbose_name=_("Quantity"))
    ship = models.ForeignKey(
        Ship,
        on_delete=models.CASCADE,
        related_name="default_assignments",
        verbose_name=_("Ship"),
    )

    def clean(self):
        if self.quantity:
            if self.quantity < 1:
                raise ValidationError(
                    {"quantity": ValidationError(_("Quantity must be at least one."))}
                )

backoffice/seawatch_registration/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _
from django_countries import Countries
from django_countries.fields import CountryField

from seawatch_registration.countries import data


class Nationalities(Countries):
    override = ((d["code"], _(d["demonym"] or d["name"])) for d in data)


class Skill(models.Model):
    name = models.CharField(max_length=50, verbose_name=_("Name"))
    description = models.CharField(
        max_length=500, blank=True, verbose_name=_("Description")
    )
    SKILL_GROUPS = [("lang", _("language")), ("other", _("other"))]
    group = models.CharField(max_length=10, choices=SKILL_GROUPS)

    def __str__(self):
        return self.name


class Position(models.Model):
    name = models.CharField(max_length=100, verbose_name=_("Name"))

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    citizenship = CountryField(
        countries=Nationalities, multiple=True, verbose_name=_("Citizenship")
    )
    date_of_birth = models.DateField(verbose_name=_("Date of birth"))
    place_of_birth = models.CharField(max_length=100, verbose_name=_("Place of birth"))
    country_of_birth = CountryField(verbose_name=_("Country of birth"))
    GENDER_CHOICES = [("f", _("female")), ("m", _("male")), ("d", _("diverse"))]
    gender = models.CharField(
        max_length=1, choices=GENDER_CHOICES, verbose_name=_("Gender")
    )
    address = models.CharField(max_length=200, blank=True, verbose_name=_("Address"))
    needs_schengen_visa = models.BooleanField(verbose_name=_("Needs Schengen Visa"))
    phone = models.CharField(max_length=100, verbose_name=_("Phone"))
    emergency_contact = models.TextField(
        blank=True, verbose_name=_("Emergency contact")
    )
    comments = models.TextField(blank=True, verbose_name=_("Comments"))
    skills = models.ManyToManyField(Skill, verbose_name=_("Skills"))
    custom_skills = models.CharField(
        max_length=500, blank=True, verbose_name=_("Custom skills")
    )
    requested_positions = models.ManyToManyField(
        Position,
        related_name="requested_profiles",
        verbose_name=_("Requested Positions"),
    )
    approved_positions = models.ManyToManyField(
        Position,
        related_name="approved_profiles",
        blank=True,
        verbose_name=_("Approved Positions"),
    )

    def __str__(self):
        return self.user.last_name + ", " + self.user.first_name

    def get_joined_citizenship_list(self, delimiter=", "):
        return delimiter.join(c.name for c in self.citizenship)


class DocumentType(models.Model):
    name = models.CharField(max_length=100, verbose_name=_("Name"))
    DOCUMENT_TYPE_GROUPS = [
        ("ident", _("identification documents and visa")),
        ("nautic", _("nautical qualification")),
        ("engineer", _("engineer qualification")),
        ("seafarer", _("seafarer qualification")),
        ("other", _("other qualification")),
    ]
    group = models.CharField(
        max_length=10, choices=DOCUMENT_TYPE_GROUPS, verbose_name=_("Category")
    )

    def __str__(self):
        return self.name


class Document(models.Model):
    document_type = models.ForeignKey(
        DocumentType, on_delete=models.CASCADE, verbose_name=_("Document type")
    )
    profile = models.ForeignKey(
        Profile, on_delete=models.CASCADE, verbose_name=_("Profile")
    )
    number = models.CharField(max_length=100, blank=True, verbose_name=_("Number"))
    issuing_date = models.DateField(
        null=True, blank=True, verbose_name=_("Issuing date")
    )
    expiry_date = models.DateField(null=True, blank=True, verbose_name=_("Expiry date"))
    issuing_authority = models.CharField(
        max_length=100, blank=True, verbose_name=_("Issuing authority")
    )
    issuing_place = models.CharField(
        max_length=100, blank=True, verbose_name=_("Issuing place")
    )
    issuing_country = models.CharField(
        max_length=100, blank=True, verbose_name=_("Issuing country")
    )
    file = models.FileField(verbose_name=_("File"))

    def __str__(self):
        return f"{self.number} ({self.document_type})"


class Question(models.Model):
    text = models.CharField(max_length=500, verbose_name=_("Text"))
    mandatory = models.BooleanField(verbose_name=_("Madatory"))
    profiles = models.ManyToManyField(
        Profile, through="Answer", verbose_name=_("Profiles")
    )

    def __str__(self):
        return self.text


class Answer(models.Model):
    profile = models.ForeignKey(
        Profile, on_delete=models.CASCADE, verbose_name=_("Profile")
    )
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, verbose_name=_("Question")
    )
    text = models.TextField(verbose_name=_("Text"))

    def __str__(self):
        return self.text


class Availability(models.Model):
    profile = models.ForeignKey(
        Profile, on_delete=models.CASCADE, verbose_name=_("Profile")
    )
    start_date = models.DateField(verbose_name=_("Start date"))
    end_date = models.DateField(verbose_name=_("End date"))
    comment = models.CharField(max_length=255, blank=True, verbose_name=_("Comment"))

    def __str__(self):
        return f'{self.start_date.strftime("%x")} – {self.start_date.strftime("%x")} ({self.profile})'

    def clean(self):
        if self.start_date and self.end_date:
            if self.start_date > self.end_date:
                raise ValidationError(
                    {
                        "start_date": ValidationError(
                            _("Cannot select an empty date range.")
                        ),
                        "end_date": ValidationError(
                            _("Cannot select an empty date range.")
                        ),
                    }
                )

backoffice/seawatch_registration/views/availability.py
import django.views.generic as generic
from django.forms import inlineformset_factory
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from seawatch_registration.mixins import HasProfileMixin, RegistrationStepOrderMixin
from seawatch_registration.models import Availability, Profile
from seawatch_registration.widgets import CustomDateInput


class CreateView(HasProfileMixin, generic.CreateView):
    model = Availability
    fields = ["start_date", "end_date", "comment"]
    nav_item = "availabilities"
    submit_button = _("Add")
    success_url = reverse_lazy("availability_list")

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        form.instance.profile = profile
        return super(CreateView, self).form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["start_date"].widget = CustomDateInput()
        form.fields["end_date"].widget = CustomDateInput()
        return form


class AvailabilityListView(
    HasProfileMixin, RegistrationStepOrderMixin, generic.FormView
):
    nav_item = "availabilities"
    title = _("Availabilities")
    success_alert = _("Available dates have been saved!")
    submit_button = _("Save")
    template_name = "./seawatch_registration/availability_list.html"
    success_url = reverse_lazy("availability_list")

    AvailableDatesFormset = inlineformset_factory(
        Profile,
        Availability,
        fields=("start_date", "end_date", "comment"),
        widgets={"start_date": CustomDateInput, "end_date": CustomDateInput},
        extra=0,
        max_num=4,
        min_num=1,
        can_delete=True,
    )

    def get_form_class(self):
        return self.AvailableDatesFormset

    def get_form_kwargs(self):
        return {**super().get_form_kwargs(), "instance": self.request.user.profile}

    def get_context_data(self, **kwargs):
        return {**super().get_context_data(**kwargs), "formset": self.get_form()}

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

backoffice/seawatch_registration/views/index.py
from django.views.generic.base import TemplateView

from ..models import Position


class IndexView(TemplateView):
    nav_item = "index"
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["all_positions"] = Position.objects.all()
        return context_data

backoffice/seawatch_registration/templates/base-registration.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    SeaWatch - {% trans 'Registration' %}
{% endblock %}

backoffice/seawatch_registration/templates/base.html
{% load bootstrap4 %}
{% load static %}
{% load fontawesome_5 %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% bootstrap_css %}
        {% fontawesome_5_static %}

        <link rel="stylesheet" href="{% static 'seawatch_registration/css/seawatch_registration.css' %}">

        <title>{% block title %}SeaWatch{% endblock %}</title>

        {% block head %}{% endblock %}
        {% bootstrap_javascript jquery="slim" %}
    </head>
    <body>
        {% include 'navbar.html' %}

        <div class="container">
            {% include 'partials/messages.html' %}

            {% block content %}{% endblock %}
        </div>
    </body>
</html>

backoffice/seawatch_registration/templates/confirm-delete.html
{% extends 'base-registration.html' %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %}{{ view.title }} | Seawatch Registration{% endblock %}

{% block content %}
    <h1>{{ view.title }}</h1>

    <form method="post">
        {% csrf_token %}
        <p>{% blocktrans with object=object%}Are you sure you want to delete "{{ object }}"?{% endblocktrans %}</p>
        <input class="btn btn-primary" type="submit" value="{% trans 'Confirm' %}">
    </form>
{% endblock %}

backoffice/seawatch_registration/templates/form.html
{% extends 'base-registration.html' %}
{% load bootstrap4 %}

{% block title %}{{ view.title }} | Seawatch Registration{% endblock %}

{% block content %}
    <h1>{{ view.title }}</h1>
    {% if success or request.GET.success %}
        <div class="alert alert-success" role="alert">
            {{ view.success_message }}
            {{ view.success_alert }}
        </div>
    {% endif %}
    {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {{ view.error_message }}
        </div>
    {% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button type="submit" class="btn btn-primary">{{ view.submit_button }}</button>
            {% if view.can_be_skipped %}
                <button form="skip_form" name="skip" value="skip" type="submit"
                        class="btn btn-link">{{ view.skip_button_text }}</button>
            {% endif %}
        {% endbuttons %}
    </form>

    {% if view.can_be_skipped %}
        <form method="post" id="skip_form">
            {% csrf_token %}
        </form>
    {% endif %}
{% endblock %}

backoffice/seawatch_registration/templates/index.html
{% extends 'base-registration.html' %}
    {% load bootstrap4 %}

    {% block title %}Seawatch Registration{% endblock %}



    {% block content %}
        <h1>Willkommen zurück {{ request.user.username }}</h1>
        <p> Siehe <a href="{% url "application_list" %}">alle Bewerbungen</a>
            oder nach Position gefiltert:
        </p>
        <ul>
            {% for position in all_positions %}
                <li>
                    <a href="{% url "application_list" %}?position={{ position.name|urlencode }}">
                        {{ position.name|capfirst }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% endblock %}

backoffice/seawatch_registration/templates/navbar.html
{% load bootstrap4 %}
{% load static %}
{% load i18n %}


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">
        <img src="{% static 'seawatch_registration/images/logo.png' %}" width="70" height="64"
             class="d-inline-block align-top mr-2" alt="">
        <!--Sea Watch-->
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="nav navbar-nav">
            <li class="nav-item">
                <a class="nav-link {% if view.nav_item == 'index' %}active{% else %}{{ view.nav_item }}{% endif %}"
                   href="{% url 'index' %}">{% trans "Home" %}</a>
            </li>
            {% if request.user.is_authenticated %}
                {% if perms.assessments.can_assess_profiles %}
                    <li class="nav-item">
                        <a class="nav-link {% if view.nav_item == 'assessment' %}active{% endif %}"
                           href="{% url 'assessment_list' %}">{% trans "Assessments" %}</a>
                    </li>
                {% endif %}
                {% if perms.missions.view_mission %}
                    <li class="nav-item">
                        <a class="nav-link {% if view.nav_item == 'missions' %}active{% endif %}"
                           href="{% url 'mission_list' %}">{% trans "Missions" %}</a>
                    </li>
                {% endif %}
                {% if perms.missions.view_ship %}
                    <li class="nav-item">
                        <a class="nav-link {% if view.nav_item == 'ships' %}active{% endif %}"
                           href="{% url 'ship_list' %}">{% trans "Ships" %}</a>
                    </li>
                {% endif %}
                {% if perms.seawatch_registration.view_question %}
                    <li class="nav-item">
                        <a class="nav-link {% if view.nav_item == 'questions' %}active{% endif %}"
                           href="{% url 'question_list' %}">{% trans "Questions" %}</a>
                    </li>
                {% endif %}
                {% if request.user.profile %}
                    {% comment %}
                        FIXME: This should not be hardcoded but take the order from somewhere else.
                    {% endcomment %}
                    <li class="nav-item">
                        <a class="nav-link {% if view.nav_item == 'profile' %}active{% endif %}"
                           href="{% url 'profile_detail' %}">{% trans "Profile" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if view.nav_item == 'skills' %}active{% endif %}"
                           href="{% url 'skill_update' %}">{% trans "Skills" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if view.nav_item == 'documents' %}active{% endif %}"
                           href="{% url 'document_list' %}">{% trans "Documents" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if view.nav_item == 'positions' %}active{% endif %}"
                           href="{% url 'requested_position_update' %}">{% trans "Requested Positions" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if view.nav_item == 'questions' %}active{% endif %}"
                           href="{% url 'question_answer' %}">{% trans "Questions" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if view.nav_item == 'availabilities' %}active{% endif %}"
                           href="{% url 'availability_list' %}">{% trans "Availabilities" %}</a>
                    </li>
                {% endif %}
            {% endif %}
        </ul>
        <ul class="nav navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ request.user.first_name }} {{ request.user.last_name }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if request.user.profile %}
                            <a class="dropdown-item" href="{% url 'profile_detail' %}">{% trans "Show profile" %}</a>
                            <a class="dropdown-item" href="{% url 'registration_process' %}">{% trans "Registration Status" %}</a>
                            <div class="dropdown-divider"></div>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'password_change' %}">{% trans "Change password" %}</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">{% trans 'Logout' %}</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link
                            {% url 'login' as login_url %}{% if request.get_full_path == login_url %}active{% endif %}"
                       href="{% url 'login' %}">{% trans "Login" %}</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

backoffice/seawatch_registration/templates/pagination.html
{% load i18n %}

{% if is_paginated %}
    <nav aria-label="...">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">{% trans 'Previous' %}</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">{% trans 'Previous' %}</span>
            </li>
            {% endif %}
            {% for number in paginator.page_range %}
                {% if page_obj.number == number %}
                <li class="page-item active">
                    <span class="page-link">
                        {{ page_obj.number }}
                    <span class="sr-only">({% trans 'current' %})</span>
                    </span>
                </li>
                {% else %}
                <li class="page-item"><a class="page-link" href="{{ request.path }}?page={{ number }}">{{ number }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">{% trans 'Next' %}</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">{% trans 'Next' %}</span>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}