backoffice/missions/urls.py
from django.urls import path

from missions.views import assignment, default_assignments, mission, question, ship

urlpatterns = [
    path("", mission.ListView.as_view(), name="mission_list"),
    path("new", mission.CreateView.as_view(), name="mission_create"),
    path("<int:pk>/", mission.DetailView.as_view(), name="mission_detail"),
    path("<int:pk>/delete", mission.DeleteView.as_view(), name="mission_delete"),
    path("<int:pk>/edit", mission.UpdateView.as_view(), name="mission_update"),
    path("ships/", ship.ListView.as_view(), name="ship_list"),
    path(
        "ships/new", ship.CreateView.as_view(), name="ship_create"
    ),  # TODO: Replace 'new' with 'add'
    path("ships/<int:pk>/edit/", ship.UpdateView.as_view(), name="ship_update"),
    path("ships/<int:pk>/delete/", ship.DeleteView.as_view(), name="ship_delete"),
    path(
        "ships/<int:ship_id>/default-assignments/",
        default_assignments.ListView.as_view(),
        name="default_assignment_list",
    ),
    path(
        "ships/<int:ship_id>/default-assignments/add/",
        default_assignments.CreateView.as_view(),
        name="default_assignment_create",
    ),
    path(
        "ships/<int:ship_id>/default-assignments/<int:pk>/edit/",
        default_assignments.UpdateView.as_view(),
        name="default_assignment_update",
    ),
    path(
        "ships/<int:ship_id>/default-assignments/<int:pk>/delete",
        default_assignments.DeleteView.as_view(),
        name="default_assignment_delete",
    ),
    path(
        "<int:mission__id>/assignments/new",
        assignment.CreateView.as_view(),
        name="assignment_create",
    ),
    path(
        "<int:mission__id>/assignments/<int:pk>/delete",
        assignment.DeleteView.as_view(),
        name="assignment_delete",
    ),
    path(
        "<int:mission__id>/assignments/<int:pk>/send_mail",
        assignment.EmailView.as_view(),
        name="assignment_mail",
    ),
    path(
        "<int:mission__id>/assignments/<int:assignment__id>/assignee",
        assignment.UpdateView.as_view(),
        name="assignee",
    ),
    path("questions/", question.ListView.as_view(), name="question_list"),
    path("questions/add", question.CreateView.as_view(), name="question_create"),
    path(
        "questions/<int:pk>/delete",
        question.DeleteView.as_view(),
        name="question_delete",
    ),
    path(
        "questions/<int:pk>/edit", question.UpdateView.as_view(), name="question_update"
    ),
]

backoffice/missions/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils import FieldTracker

from seawatch_registration.models import Position


# Create your models here.
class Ship(models.Model):
    name = models.CharField(max_length=30, verbose_name=_("Name"))

    def __str__(self):
        return self.name


class Mission(models.Model):
    name = models.CharField(max_length=50, verbose_name=_("Name"))
    start_date = models.DateField(verbose_name=_("Start date"))
    end_date = models.DateField(verbose_name=_("End date"))
    ship = models.ForeignKey(Ship, on_delete=models.CASCADE, verbose_name=_("Ship"))

    def __str__(self):
        return self.ship.name + ": " + self.name

    def get_assigned_users(self):
        return User.objects.filter(assignments__mission=self).distinct()


class Assignment(models.Model):
    mission = models.ForeignKey(
        Mission, on_delete=models.CASCADE, verbose_name=_("Mission")
    )
    position = models.ForeignKey(
        Position, on_delete=models.CASCADE, verbose_name=_("Position")
    )
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        default=None,
        blank=True,
        null=True,
        related_name="assignments",
    )
    confirmed = models.BooleanField(default=False, verbose_name=_("Confirmed"))
    email_sent = models.BooleanField(default=False, verbose_name=_("Email sent"))

    tracker = FieldTracker(fields=["user"])


class DefaultAssignment(models.Model):
    position = models.ForeignKey(
        Position, on_delete=models.CASCADE, verbose_name=_("Position")
    )
    quantity = models.IntegerField(verbose_name=_("Quantity"))
    ship = models.ForeignKey(
        Ship,
        on_delete=models.CASCADE,
        related_name="default_assignments",
        verbose_name=_("Ship"),
    )

    def clean(self):
        if self.quantity:
            if self.quantity < 1:
                raise ValidationError(
                    {"quantity": ValidationError(_("Quantity must be at least one."))}
                )

backoffice/missions/views/assignment.py
from django import forms
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import User
from django.core import mail
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import generic
from django_filters import CharFilter, DateFilter, FilterSet
from django_filters.views import FilterView
from django_tables2 import SingleTableMixin

from missions.models import Assignment, Mission
from missions.tables.candidates import CandidatesTable
from seawatch_registration.models import Profile
from seawatch_registration.widgets import CustomDateInput


class ProfileFilter(FilterSet):
    start_date = DateFilter(
        widget=CustomDateInput, field_name="availability__start_date", lookup_expr="lte"
    )
    end_date = DateFilter(
        widget=CustomDateInput,
        field_name="availability__end_date",
        lookup_expr="gte",
        label=_("Avail. End."),
    )
    user__first_name = CharFilter(label="first name", lookup_expr="contains")
    user__last_name = CharFilter(label="last name", lookup_expr="contains")

    class Meta:
        model = Profile
        fields = ["user__first_name", "user__last_name", "requested_positions"]


class DeleteView(PermissionRequiredMixin, generic.DeleteView):
    model = Assignment
    nav_item = "missions"
    permission_required = "missions.delete_assignment"

    def get_success_url(self):
        return reverse("mission_detail", kwargs={"pk": self.object.mission.id})


class UpdateView(PermissionRequiredMixin, SingleTableMixin, FilterView):
    template_name = "missions/assignee_form.html"
    nav_item = "missions"
    permission_required = "missions.change_assignment"
    table_class = CandidatesTable
    filterset_class = ProfileFilter

    def get_context_data(self, **kwargs):
        mission_id = self.kwargs.pop("mission__id")
        mission = get_object_or_404(Mission, id=mission_id)
        return {**super().get_context_data(**kwargs), "mission": mission}

    def get_queryset(self, **kwargs):
        # Joins related to the ProfileFilter will cause duplicate entries.
        return Profile.objects.distinct()

    def post(self, request, *args, **kwargs):
        assignment_id = kwargs.pop("assignment__id")
        profile_id = request.POST["assignee"]
        if profile_id:
            user = get_object_or_404(User, profile__pk=profile_id)
            assignment = Assignment.objects.get(pk=assignment_id)
            assignment.user = user
            assignment.save()
            return redirect(
                reverse("mission_detail", kwargs={"pk": kwargs.pop("mission__id")})
            )


class AssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = ["position"]


class CreateView(PermissionRequiredMixin, generic.FormView):
    form_class = AssignmentForm
    template_name = "missions/assignment_form.html"
    nav_item = "missions"
    permission_required = "missions.add_assignment"

    def form_valid(self, form):
        mission = get_object_or_404(Mission, pk=self.kwargs.pop("mission__id"))
        form.instance.mission_id = mission.id
        form.save()
        return redirect(reverse("mission_detail", kwargs={"pk": mission.id}))


class EmailView(PermissionRequiredMixin, generic.View):
    nav_item = "missions"
    permission_required = "missions.add_assignment"
    template_name = "./missions/assignment_confirm_mail.html"

    def get(self, request, *args, **kwargs):
        assignment = get_object_or_404(
            Assignment, pk=kwargs.pop("pk"), mission__id=kwargs.pop("mission__id")
        )
        return render(request, self.template_name, {"assignment": assignment})

    def post(self, request, *args, **kwargs):
        assignment = get_object_or_404(
            Assignment, pk=kwargs.pop("pk"), mission__id=kwargs.pop("mission__id")
        )
        name = assignment.user.first_name + " " + assignment.user.last_name

        subject = _("Sea-Watch.org: You have been assigned to a mission")
        message2 = render_to_string(
            "missions/email_mission_assigned.html",
            {
                "name": name,
                "start_date": str(assignment.mission.start_date),
                "end_date": str(assignment.mission.end_date),
                "position": assignment.position.name,
                "ship_name": assignment.mission.ship.name,
                "stuff_name": "Sea-Watch e.V.",
            },
        )
        from_email = "team@sea-watch.org"
        recipient_list = [assignment.user.email]

        mail.send_mail(subject, message2, from_email, recipient_list)
        assignment.email_sent = True
        assignment.save()
        return redirect(reverse("mission_detail", kwargs={"pk": assignment.mission.id}))

backoffice/missions/views/default_assignments.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic

from missions.models import DefaultAssignment, Ship


class CreateView(PermissionRequiredMixin, generic.CreateView):
    model = DefaultAssignment
    fields = ["position", "quantity"]
    nav_item = "ships"
    permission_required = "missions.add_defaultassignment"

    def get_success_url(self):
        ship_id = self.kwargs.get("ship_id")
        return reverse("default_assignment_list", kwargs={"ship_id": ship_id})

    def form_valid(self, form):
        ship_id = self.kwargs.get("ship_id")
        if DefaultAssignment.objects.filter(
            position=form.cleaned_data["position"], ship=ship_id
        ).exists():
            form.add_error(
                "position",
                _(
                    "There is already a default assignment for this position for this ship!"
                ),
            )
            return self.form_invalid(form)

        form.instance.ship = get_object_or_404(Ship, pk=ship_id)
        return super().form_valid(form)


class UpdateView(PermissionRequiredMixin, generic.UpdateView):
    model = DefaultAssignment
    fields = ["position", "quantity"]
    nav_item = "ships"
    permission_required = "missions.add_defaultassignment"

    def get_success_url(self):
        ship_id = self.kwargs.get("ship_id")
        return reverse("default_assignment_list", kwargs={"ship_id": ship_id})

    def form_valid(self, form):
        ship_id = self.kwargs.get("ship_id")
        form.instance.ship = get_object_or_404(Ship, pk=ship_id)
        return super().form_valid(form)


class ListView(PermissionRequiredMixin, generic.ListView):
    model = DefaultAssignment
    paginate_by = 10
    nav_item = "ships"
    ordering = "id"
    permission_required = "missions.view_defaultassignment"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ship_id = self.kwargs.get("ship_id")
        context["ship"] = get_object_or_404(Ship, pk=ship_id)
        return context

    def get_queryset(self):
        ship_id = self.kwargs.get("ship_id")
        return DefaultAssignment.objects.filter(ship__id=ship_id)


class DeleteView(PermissionRequiredMixin, generic.DeleteView):
    model = DefaultAssignment
    nav_item = "ships"
    permission_required = "missions.delete_defaultassignment"

    def get_success_url(self):
        ship_id = self.kwargs.get("ship_id")
        return reverse("default_assignment_list", kwargs={"ship_id": ship_id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ship_id = self.kwargs.pop("ship_id")
        context["ship"] = get_object_or_404(Ship, pk=ship_id)
        return context

backoffice/missions/views/mission.py
from django import forms
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Count, Q
from django.urls import reverse, reverse_lazy
from django.views import generic as generic

from missions.models import Assignment, Mission
from seawatch_registration.widgets import CustomDateInput


class ListView(PermissionRequiredMixin, generic.ListView):
    model = Mission
    ordering = "id"
    paginate_by = 100  # if pagination is desired
    nav_item = "missions"
    permission_required = "missions.view_mission"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class DetailView(PermissionRequiredMixin, generic.DetailView):
    model = Mission
    nav_item = "missions"
    permission_required = "missions.view_mission"

    def get_context_data(self, **kwargs):
        mission = self.get_object()
        multiple_assignments_in_mission = User.objects.annotate(
            assignment_cnt=Count("assignments", filter=Q(assignments__mission=mission))
        ).filter(assignment_cnt__gt=1)

        multiple_assignments_in_different_missions = User.objects.annotate(
            assignment_cnt=Count(
                "assignments",
                filter=Q(
                    assignments__mission__start_date__range=(
                        mission.start_date,
                        mission.end_date,
                    )
                )
                | Q(
                    assignments__mission__end_date__range=(
                        mission.start_date,
                        mission.end_date,
                    )
                )
                | (
                    Q(assignments__mission__start_date__lte=mission.start_date)
                    & Q(assignments__mission__end_date__gte=mission.end_date)
                ),
            )
            - Count("assignments", filter=Q(assignments__mission=mission))
            + 1
        ).filter(assignment_cnt__gt=1)

        return {
            **super().get_context_data(**kwargs),
            "multiple_assigned_users": multiple_assignments_in_mission,
            "multiple_assigned_users_in_different_missions": multiple_assignments_in_different_missions,
        }


class MissionCreateForm(forms.ModelForm):
    create_default_assignments = forms.BooleanField(required=False, initial=True)

    class Meta:
        model = Mission
        fields = [
            "name",
            "start_date",
            "end_date",
            "ship",
            "create_default_assignments",
        ]
        widgets = {"start_date": CustomDateInput(), "end_date": CustomDateInput()}


class CreateView(PermissionRequiredMixin, generic.CreateView):
    model = Mission
    form_class = MissionCreateForm
    nav_item = "missions"
    permission_required = "missions.add_mission"

    def get_success_url(self):
        return reverse("mission_detail", kwargs={"pk": self.object.id})

    def form_valid(self, form):
        mission = form.save()
        if form.cleaned_data["create_default_assignments"]:
            self._create_default_assignments(mission)
        return super().form_valid(form)

    @staticmethod
    def _create_default_assignments(mission):
        for default_assignment in mission.ship.default_assignments.all():
            for _ in range(default_assignment.quantity):
                Assignment.objects.create(
                    mission=mission, position=default_assignment.position
                )


class DeleteView(PermissionRequiredMixin, generic.DeleteView):
    model = Mission
    nav_item = "missions"
    success_url = reverse_lazy("mission_list")
    permission_required = "missions.delete_mission"


class UpdateView(PermissionRequiredMixin, generic.UpdateView):
    model = Mission
    nav_item = "missions"
    fields = ["name", "start_date", "end_date", "ship"]
    success_url = reverse_lazy("mission_list")
    permission_required = "missions.change_mission"

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["start_date"].widget = CustomDateInput()
        form.fields["end_date"].widget = CustomDateInput()
        return form

backoffice/missions/views/ship.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views import generic

from missions.models import Ship


class CreateView(PermissionRequiredMixin, generic.CreateView):
    model = Ship
    fields = ["name"]
    nav_item = "ships"
    permission_required = "missions.add_ship"
    success_url = reverse_lazy("ship_list")


class UpdateView(PermissionRequiredMixin, generic.UpdateView):
    model = Ship
    fields = ["name"]
    nav_item = "ships"
    permission_required = "missions.change_ship"
    success_url = reverse_lazy("ship_list")


class ListView(PermissionRequiredMixin, generic.ListView):
    model = Ship
    ordering = "name"
    paginate_by = 10
    nav_item = "ships"
    permission_required = "missions.view_ship"


class DeleteView(PermissionRequiredMixin, generic.DeleteView):
    model = Ship
    nav_item = "ships"
    success_url = reverse_lazy("ship_list")
    permission_required = "missions.delete_ship"

backoffice/missions/templates/missions/assignment_confirm_delete.html
{% extends 'base-registration.html' %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %}Missions | Seawatch Missions{% endblock %}

{% block content %}
    <h1>
        {% blocktrans trimmed with position_name=object.position.name mission_name=object.mission.name %}
        Delete assignment "{{ position_name }}" for mission "{{ mission_name }}"
        {% endblocktrans %}
    </h1>

    <form method="post">{% csrf_token %}
        <p>
            {% blocktrans trimmed with position_name=object.position.name mission_name=object.mission.name%}
            Are you sure you want to delete assignment "{{ position_name }}" for mission "{{ mission_name }}"?
            {% endblocktrans %}
        </p>
        <input class="btn btn-primary" type="submit" value="{% trans 'Confirm' %}">
        <a class="btn btn-primary"href="{% url 'mission_detail' object.mission.id %}" role="button">{% trans "Cancel" %}</a>
    </form>
{% endblock %}

backoffice/missions/templates/missions/assignment_confirm_mail.html
{% extends 'base-registration.html' %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %}Missions | Seawatch Missions{% endblock %}

{% block content %}
    <h1>
        {% blocktrans trimmed with first_name=assignment.user.first_name last_name=assignment.user.last_name %}
        Send assignment email to {{ first_name }} {{ last_name }}
        {% endblocktrans %}
    </h1>

    <form method="post">{% csrf_token %}
        <p>
            {% blocktrans trimmed with first_name=assignment.user.first_name last_name=assignment.user.last_name %}
            Are you sure you want to send a assignment email to {{ first_name }} {{ last_name }}?
            {% endblocktrans %}
        </p>
        <input class="btn btn-primary" type="submit" value="{% trans 'Confirm' %}"> <a class="btn btn-primary"href="{% url 'mission_detail' assignment.mission.id %}" role="button">{% trans "Cancel" %}</a>
    </form>
{% endblock %}

backoffice/missions/templates/missions/assignment_form.html
{% extends "base-missions.html" %}
{% load bootstrap4 %}

{% block content %}

    <h1>{% trans "Create new position" %}</h1>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn btn-primary" type="submit" value="{% trans 'Save' %}">
    </form>

{% endblock %}

backoffice/missions/templates/missions/defaultassignment_confirm_delete.html
{% extends 'base-registration.html' %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %}Default Assignment | Seawatch Missions{% endblock %}

{% block content %}
    <h1>{% blocktrans with quantity=object.quantity position=object.position ship_name=ship.name %}Delete default assignment "{{ quantity }}x {{ position }}" of ship "{{ ship_name }}"{% endblocktrans %}</h1>

    <form method="post">{% csrf_token %}
        <p>{% blocktrans with quantity=object.quantity position=object.position ship_name=ship.name %}Are you sure you want to delete default assignment "{{ quantity }}x {{ position }}" of ship "{{ ship_name }}"?{% endblocktrans %}</p>
        <input class="btn btn-primary" type="submit" value="{% trans 'Confirm' %}"> <a class="btn btn-primary"href="{% url 'default_assignment_list' ship.id %}" role="button">{% trans 'Cancel' %}</a>
    </form>
{% endblock %}

backoffice/missions/templates/missions/defaultassignment_detail.html
{% extends 'base-registration.html' %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %}Mission | Seawatch Missions{% endblock %}

{% block content %}
<h1>{% blocktrans with name=obejct.name %}Ship {{ name }}{% endblocktrans %}</h1>
<p><strong>{% trans 'Name:' %} </strong>{{ object.name }}</p>
{% endblock %}

backoffice/missions/templates/missions/defaultassignment_form.html
{% extends 'base-registration.html' %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %}Default Assignment | Seawatch Missions{% endblock %}

{% block content %}
<h1>{% trans 'Default Assignment' %}</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}

    <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
</form>
{% endblock %}

backoffice/missions/templates/missions/defaultassignment_list.html
{% extends "base-missions.html" %}
{% load bootstrap4 %}
{% load fontawesome_5 %}
{% load i18n %}

{% block content %}
<h1>{% trans 'Default Assignments' %}</h1>
{% if object_list %}
<table class="table table-hover">
    <thead>
        <tr>
            <th>{% trans 'Position' %}</th>
            <th>{% trans 'Quantity' %}</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for default_assignment in object_list %}
        <tr>
            <td>{{ default_assignment.position }}</td>
            <td>{{ default_assignment.quantity }}</td>
            <td>
                <a href="{% url 'default_assignment_update' ship.id default_assignment.id %}" data-toggle="tooltip" title="edit">{% fa5_icon 'edit' 'fas' %}</a>
                <a class="text-danger" href="{% url 'default_assignment_delete' ship.id default_assignment.id %}" data-toggle="tooltip" title="delete">{% fa5_icon 'trash' 'fas' %}</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
    <p>{% trans 'No default assignments yet.' %}</p>
{% endif %}
<a class="btn btn-primary" href="{% url 'default_assignment_create' ship.id%}" role="button">{% fa5_icon 'plus' 'fas' %}</a>
{% endblock %}

backoffice/missions/templates/missions/email_mission_assigned.html
{% extends "missions/email_base.html" %}

{% block preview %}
You got assigned to a mission!
{% endblock %}

{% block content %}
<p>Hi {{ name }},</p>
<p>You have been assigned to a Sea-Watch rescue mission.</p>
<p>The mission starts at the {{ start_date }} and ends at the {{ end_date }}.</p>
<p>You will be {{ position }} at the {{ ship_name }}</p>
<p>Please confirm that you participate at this mission, such that the mission can be prepare with all regulatory stuff.</p>
<table role="presentation" border="0" cellpadding="0" cellspacing="0" class="btn btn-primary">
    <tbody>
        <tr>
            <td align="left">
                <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                    <tbody>
                        <tr>
                            <td> <a href="http://htmlemail.io" target="_blank">Confirm you participation!</a> </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>
<p>Thank you really much for your voluntary work at Sea-Watch!</p>
<p>We will inform you soon with further information.</p>
<br>
<p>Sincerely yours,</p>
<p>{{ stuff_name }}</p>
{% endblock %}


{% block footer %}
<span class="apple-link">Verein Sea-Watch e.V., c/o dka-Anwälte, Immanuelkirchstraße 3-4, 10405 Berlin, Germany</span>
{% endblock %}

backoffice/missions/templates/missions/mission_confirm_delete.html
{% extends 'base-registration.html' %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %}Missions | Seawatch Missions{% endblock %}

{% block content %}
    <h1>{% blocktrans with name=object.name %}Delete missison "{{ name }}"{% endblocktrans %}</h1>

    <form method="post">{% csrf_token %}
        <p>{% blocktrans with name=object.name %}Are you sure you want to delete mission "{{ name }}"?{% endblocktrans %}</p>
        <input class="btn btn-primary" type="submit" value="{% trans 'Confirm' %}"> <a class="btn btn-primary"href="{% url 'mission_list' %}" role="button">{% trans 'Cancel' %}</a>
    </form>
{% endblock %}

backoffice/missions/templates/missions/mission_detail.html
{% extends "base-missions.html" %}
{% load bootstrap4 %}
{% load fontawesome_5 %}
{% load i18n %}


{% block content %}
<script type="text/javascript">
function AlertMultipleAssignmentsInSameMission(first_name, last_name) {
alert(first_name + " " + last_name + " is assigned multiple times for this mission")
}
function AlertMultipleAssignmentsInDifferentMission(first_name, last_name) {
alert(first_name + " " + last_name + " is assigned to a different mission in the same timeperiod")
}
</script>

<h1>{% blocktrans with ship_name=object.ship.name mission_name=object.name %}{{ ship_name }}: Mission ”{{ mission_name }}”{% endblocktrans %}</h1>
<p>{% blocktrans with start_date=object.start_date end_date=object.end_date%}From {{ start_date }} to {{ end_date }}{% endblocktrans %}</p>
<h2>{% trans 'Assignments' %}</h2>
<table class="table">
    <thead>
    <tr>
        {% if multiple_assigned_users or multiple_assigned_users_in_different_missions%}
        <th scope="col"></th>
        {% endif %}
        <th scope="col">{% trans 'Position' %}</th>
        <th scope="col">{% trans 'Assignment' %}</th>
        <th scope="col">{% trans 'Confirmation' %}</th>
        <th scope="col">{% trans 'Actions' %}</th>
    </tr>
    </thead>
    <tbody>
    {% for assignment in object.assignment_set.all %}
    <tr>
        {% if multiple_assigned_users or multiple_assigned_users_in_different_missions %}

        <td>
            {% if assignment.user in multiple_assigned_users %}
            <a class="text-danger" href="javascript:AlertMultipleAssignmentsInSameMission('{{ assignment.user.first_name}}','{{assignment.user.last_name}}');">
                {% fa5_icon 'exclamation-triangle' 'fas' %}
            </a>
            {% endif %}
            {% if assignment.user in multiple_assigned_users_in_different_missions %}
            <a class="text-danger" href="javascript:AlertMultipleAssignmentsInDifferentMission('{{ assignment.user.first_name}}','{{assignment.user.last_name}}');">
                {% fa5_icon 'exclamation-triangle' 'fas' %}
            </a>
            {% endif %}
        </td>
        {% endif %}
        <td>{{ assignment.position.name }}</td>
        <td>{{ assignment.user.first_name }} {{ assignment.user.last_name }}</td>
        <td>{{ assignment.confirmed }}</td>
        <td>
            <a href="{% url 'assignee' object.id assignment.id %}"  data-toggle="tooltip" title="{% comment %}Translators: Text for Tooltip{% endcomment %}{% trans 'assign volunteer' %}">
                {% fa5_icon 'user' 'fas' %}
            </a>
            {% if not assignment.email_sent and assignment.user %}
            <a href="{% url 'assignment_mail' object.id assignment.id %}"  data-toggle="tooltip" title="{% comment %}Translators: Text for Tooltip{% endcomment %}{% trans 'send mission information email' %}">
                {% fa5_icon 'envelope' 'fas' %}
            </a>
            {% else %}
            <a class="text-black-50" data-toggle="tooltip" title="{% comment %}Translators: Text for Tooltip{% endcomment %}{% trans 'send mission information email' %}">
                {% fa5_icon 'envelope' 'fas' %}
            </a>
            {% endif %}
            <a class="text-danger" href="{% url 'assignment_delete' object.id assignment.id %}"  data-toggle="tooltip" title="{% comment %}Translators: Text for Tooltip{% endcomment %}{% trans 'delete' %}">
                {% fa5_icon 'trash' 'fas' %}
            </a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<a class="btn btn-primary" href="{% url 'assignment_create' object.id %}" role="button">{% fa5_icon 'plus' 'fas' %}</a>
{% endblock %}